spring:
  application:
    name: kafka-streams-aggregate-sample4
  cloud:
    stream:
      function:
        definition: aggregateRuleResult,aggregateActionResult
      kafka:
        streams:
          binder:
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              commit.interval.ms: 1000
          bindings:
            aggregateRuleResult-in-0:
              clientId: aggregate-rule-result-consumer
            aggregateActionResult-in-0:
              clientId: aggregate-action-result-consumer
      bindings:
        aggregateRuleResult-in-0:
          destination: rule-engine.execution.result
        aggregateRuleResult-out-0:
          destination: rule-engine.aggregated-rule-result

        aggregateActionResult-in-0:
          destination: rule-engine.action.result